CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	email varchar(100) NOT NULL,
	password varchar(100) NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_email UNIQUE (email)
);
COMMENT ON TABLE public.users IS 'This entity represents an user';

CREATE TABLE public.nodes (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_user int8 not null,
	id_parent_node int8 NULL,
	creation_date_time timestamp NOT NULL,
	"name" varchar(200) NOT NULL,
	node_type varchar(15) NOT NULL,
	"size" int8 NULL,
	s3_key varchar(1024) NULL,
	CONSTRAINT nodes_pk PRIMARY KEY (id),
	CONSTRAINT nodes_s3_key UNIQUE (s3_key),
	CONSTRAINT nodes_nodes_fk FOREIGN KEY (id_parent_node) REFERENCES public.nodes(id),
	constraint nodes_user_fk foreign key (id_user) references public.users(id),
	constraint nodes_name_parent_unique unique (id_parent_node, "name")
);
COMMENT ON TABLE public.nodes IS 'This entity represents a file node';
